//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalPortfolio3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Description
    {
        public int ScreenshotID { get; set; }
        public int ProjectDescriptionID { get; set; }
        public string ProjectDescription { get; set; }
    
        public virtual Screenshot Screenshot { get; set; }
    }
}
